name: env_l2hmc
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - tensorflow==1.15
  - pip:
    - tensorflow-estimator==1.15.1
  - scipy
  - numpy==1.19.5
  - matplotlib
  - ipykernel
